### ISSUE TITLE
[BUG] - cant select anything

### ISSUE THREAD

**Issue by Profoundant89** [eastcw/foundryvtt-dnd5eCharacterActions#10] opened 2024-02-17 18:23 UTC
**Describe the bug**
none of the actions listed in the action tab are actually selectable, i only noticed this working after the dnd beyond merger, but i also hadnt played in like a month. 

**To Reproduce**
If there are any specific steps needed to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Version**
using the latest stable version.

**Comment by eastcw** [comment] 2024-03-16 17:31
This has been caused by the new 5e 3.0 system release and should be fixed by the next release. Sorry for the wait!

**Closed as completed** 2024-03-18 09:53 UTC
Labels: bug
