### ISSUE TITLE
[BUG] Cannot use any actions since DnD 5e 3.0+ updates

### ISSUE THREAD

**Issue by jrbuda** [eastcw/foundryvtt-dnd5eCharacterActions#13] opened 2024-03-16 11:11 UTC
**Describe the bug**
When trying to use the actions tab post 3.0.x+ updates, nothing gets rolled to chat. No other modules installed.

**To Reproduce**
If there are any specific steps needed to reproduce the behavior:

Open a character sheet
Navigate to actions
Click an action

**Expected behavior**
A roll dialog option of some kind should be started but instead an error is thrown:
`Uncaught TypeError: app._onItemUse is not a function
    addActionsTab foundryvtt-dnd5eCharacterActions.js:54
    jQuery 9
    addActionsTab foundryvtt-dnd5eCharacterActions.js:54
    async* foundryvtt-dnd5eCharacterActions.js:131
    #call foundry.js:730
    callAll foundry.js:687
    _render foundry.js:5855
    _render foundry.js:6532
    render foundry.js:5769
    render foundry.js:7111
    _onClickLeft2 foundry.js:56272
    callback foundry.js:31766
    #handleClickLeft2 foundry.js:31971
    #handleMouseDown foundry.js:31938
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
    addEvents earcut.js:128
    setTargetElement earcut.js:128
    init earcut.js:128
    emit index.mjs:5
    run index.js:89
    un index.js:126
    wa index.js:89
    xn earcut.js:128
    #createApplication foundry.js:26327
    initialize foundry.js:26223
    initializeCanvas foundry.js:8894
    setupGame foundry.js:8724
    _initializeGameView foundry.js:9990
    _initializeView foundry.js:9966
    initialize foundry.js:8650
    async* foundry.js:91833
    async* foundry.js:91809
3 foundryvtt-dnd5eCharacterActions.js:54:66
    addActionsTab foundryvtt-dnd5eCharacterActions.js:54
    jQuery 9
    addActionsTab foundryvtt-dnd5eCharacterActions.js:54
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> foundryvtt-dnd5eCharacterActions.js:131
    #call foundry.js:730
    callAll foundry.js:687
    _render foundry.js:5855
    AsyncFunctionNext self-hosted:852
    (Async: async)
    _render foundry.js:6532
    render foundry.js:5769
    render foundry.js:7111
    _onClickLeft2 foundry.js:56272
    callback foundry.js:31766
    #handleClickLeft2 foundry.js:31971
    #handleMouseDown foundry.js:31938
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
    (Async: EventListener.handleEvent)
    addEvents earcut.js:128
    setTargetElement earcut.js:128
    init earcut.js:128
    emit index.mjs:5
    run index.js:89
    un index.js:126
    wa index.js:89
    xn earcut.js:128
    #createApplication foundry.js:26327
    initialize foundry.js:26223
    initializeCanvas foundry.js:8894
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    setupGame foundry.js:8724
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    _initializeGameView foundry.js:9990
    _initializeView foundry.js:9966
    initialize foundry.js:8650
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> foundry.js:91833
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> foundry.js:91809
`

**Screenshots**
![image](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/assets/47678481/7b938822-221d-49cc-b03f-2803ceb779e2)

**Version**
Foundry v11 Stable 315
DnD 5e v3.0.5

**Comment by d20an** [comment] 2024-03-16 14:55
Did this work pre 3.0? We roll physical dice so never noticed. If it should work, I'll see if I can update my patch to fix it.

**Comment by eastcw** [comment] 2024-03-16 17:31
This has been caused by the new 5e 3.0 system release and should be fixed by the next release. Sorry for the wait!

**Comment by jrbuda** [comment] 2024-03-16 21:27
Thank you! I will wait until the module is updated to reintroduce it into my campaign.

**Comment by eastcw** [comment] 2024-03-16 22:30
I've released a beta version here on Github if you want to try it now, otherwise if there are no isues with my group this weekend I'll try and get the Foundry release out after that.

**Comment by jrbuda** [comment] 2024-03-16 22:55
I have not installed a module just from a github link before, only with a modules.json file link. Do I just copy paste the src folder from the beta branch into my module folder? Because that did not work either

**Comment by eastcw** [comment] 2024-03-16 23:04
That's fine! You can go to the releases section on the right hand side of the repository main page, and find the v7.0.0-beta1 release on there. At the bottom look for the assets associated with the release, and then you can right click and copy the address of the module.json file from there and copy that into Foundry. It will install over the current version you have like a normal Foundry update.
![image](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/assets/25549143/292155b3-6c31-4acd-826d-9412dfae9dd8)

**Comment by jrbuda** [comment] 2024-03-16 23:05
Missed that completely, thank you!

**Comment by jrbuda** [comment] 2024-03-16 23:08
Just did a quick smoke test and it seems to be working as intended. Have my session tomorrow and it will get some use then too so I can follow up if I find anything. Thanks!

**Closed as completed** 2024-03-18 09:53 UTC
Labels: bug
